# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Calculator-SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Calculator-SwiftUI

  target 'Calculator-SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'ViewInspector'
  end

  target 'Calculator-SwiftUIUITests' do
    # Pods for testing
  end

end
