name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest # to take advantage of hardware acceleration
    
    strategy:
      fail-fast: false
      matrix:
        dir: ['./Calculator-View', './Calculator-Compose']
        api-level: [27, 29, 31]
    
    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit tests
      run: ./gradlew test

    - name: Run instrumentation tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: x86_64
        working-directory: ${{ matrix.dir }}
        script: ./gradlew connectedCheck

    # The test results are shown as a webpage instead of on the command line
    - name: Upload Reports
      if: always() # show reports even if the previous steps fail
      uses: actions/upload-artifact@v1
      with:
        name: reports-${{ matrix.dir }}-${{ matrix.api-level }}
        path: ${{ matrix.dir }}/app/build/reports

