name: Android CI

on:
  push:
    branches: [main]
    paths:
      - "Calculator-View/**"
      - "Calculator-Compose/**"
      - ".github/workflows/android.yml"
  pull_request:
    branches: [main]
    paths:
      - "Calculator-View/**"
      - "Calculator-Compose/**"
      - ".github/workflows/android.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        dir: ["./Calculator-View", "./Calculator-Compose"]
        api-level: [30, 32, 34]

    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - uses: actions/checkout@v4

      # Kernel-based Virtual Machine (to enhance the performance of AVDs)
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          target: google_apis
          working-directory: ${{ matrix.dir }}
          script: ./gradlew connectedCheck

      # The test results are shown as a webpage instead of on the command line
      - name: Upload Reports
        if: always() # show reports even if the previous steps fail
        uses: actions/upload-artifact@v4
        with:
          # Ideally this should indicate whether this is View or Compose, but the job index is the next best thing
          name: reports-${{ matrix.api-level }}-${{ strategy.job-index }}
          path: ${{ matrix.dir }}/app/build/reports
