name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest # to take advantage of hardware acceleration
    
    strategy:
      matrix:
        dir: ['./Calculator-View', './Calculator-Compose']
        api-level: [27, 29, 31]
    
    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit tests
      run: ./gradlew test

    - name: Run instrumentation tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: x86_64
        working-directory: ${{ matrix.dir }}
        script: ./gradlew connectedCheck
